# Generated by Django 5.2.12 on 2026-03-22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(blank=True, help_text='Auto-generated internal ID. Can be edited.', max_length=10, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('isbn', models.CharField(blank=True, max_length=13)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['book_id'],
                'verbose_name': 'Book Title',
                'verbose_name_plural': 'Book Titles',
            },
        ),
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copy_id', models.CharField(blank=True, help_text='Auto-generated unique copy ID (e.g., #01-1, #01-2)', max_length=15, unique=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('on_loan', 'On Loan'), ('damaged', 'Damaged'), ('lost', 'Lost'), ('retired', 'Retired')], default='available', max_length=20)),
                ('condition', models.CharField(blank=True, help_text="Condition notes (e.g., 'Good', 'Fair', 'Needs repair')", max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='books.book')),
            ],
            options={
                'ordering': ['copy_id'],
                'verbose_name': 'Book Copy',
                'verbose_name_plural': 'Book Copies',
            },
        ),
    ]
