# Generated by Django 5.2.12 on 2026-03-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branding',
            name='logo_invert',
            field=models.BooleanField(default=True, help_text='Invert logo colors (for dark backgrounds)'),
        ),
        migrations.AddField(
            model_name='branding',
            name='show_company_name',
            field=models.BooleanField(default=True, help_text='Show company name below logo'),
        ),
        migrations.AddField(
            model_name='branding',
            name='show_library_name',
            field=models.BooleanField(default=True, help_text='Show library name below logo'),
        ),
        migrations.AlterField(
            model_name='branding',
            name='company_name',
            field=models.CharField(blank=True, default='AeroConnections', max_length=100),
        ),
    ]
