# Generated by Django 5.2.12 on 2026-03-21 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_branding_logo_invert_branding_show_company_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibrarySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_duration_days', models.PositiveIntegerField(choices=[(14, '14 days'), (21, '21 days'), (30, '30 days'), (45, '45 days'), (60, '60 days')], default=30, help_text='Default loan duration for new loans')),
                ('due_soon_threshold', models.PositiveIntegerField(choices=[(21, '21 days before due'), (25, '25 days before due'), (28, '28 days before due')], default=25, help_text="Days before due date to mark as 'Due Soon'")),
                ('max_books_per_borrower', models.PositiveIntegerField(default=5, help_text='Maximum books a borrower can have on loan at once')),
                ('notify_on_checkout', models.BooleanField(default=False, help_text='Send notification when a book is checked out')),
                ('notify_on_return', models.BooleanField(default=False, help_text='Send notification when a book is returned')),
                ('notify_on_overdue', models.BooleanField(default=False, help_text='Send notification when a book becomes overdue')),
                ('webhook_url', models.URLField(blank=True, help_text='Webhook URL to send notifications (e.g., Slack, Discord, custom)')),
                ('webhook_secret', models.CharField(blank=True, help_text='Secret key for webhook authentication', max_length=255)),
                ('email_notifications_enabled', models.BooleanField(default=False, help_text='Enable email notifications')),
                ('email_host', models.CharField(blank=True, help_text='SMTP server hostname', max_length=255)),
                ('email_port', models.PositiveIntegerField(blank=True, default=587, help_text='SMTP server port')),
                ('email_username', models.EmailField(blank=True, help_text='SMTP username', max_length=254)),
                ('email_password', models.CharField(blank=True, help_text='SMTP password (will be encrypted in production)', max_length=255)),
                ('email_from_address', models.EmailField(blank=True, help_text='From address for outgoing emails', max_length=254)),
                ('email_use_tls', models.BooleanField(default=True, help_text='Use TLS encryption for email')),
                ('overdue_reminder_days', models.PositiveIntegerField(default=7, help_text='Days after due date to send overdue reminder')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Library Settings',
                'verbose_name_plural': 'Library Settings',
            },
        ),
    ]
