# Generated by Django 5.2.12 on 2026-03-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_librarysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarysettings',
            name='google_sheets_id',
            field=models.CharField(blank=True, help_text='Google Sheets ID for data backup (found in spreadsheet URL)', max_length=255),
        ),
    ]
